project:
  type: website
  output-dir: docs

website:
  title: "Prova2"
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - text: Project
        menu:
          - href: VAIAK1.qmd
            text: Che cos'è il VAIAK
          - href: VAIAK2.qmd
            text: Validazione
          - href: VAIAK3.qmd
            text: Analisi CFA
          - href: VAIAK4.qmd
            text: Analisi IRT

format:
  html:
    theme: cosmo