project:
  type: website
  output-dir: docs   # cartella dove verrà generato il sito HTML

website:
  title: "Prova2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Sezione 1
        menu:
          - href: pagina1.qmd
            text: Pagina 1
          - href: pagina2.qmd
            text: Pagina 2
      - text: Sezione 2
        menu:
          - href: pagina3.qmd
            text: Pagina 3

format:
  html:
    theme: cosmo 