project:
  type: website
  output-dir: docs   # cartella dove verrà generato il sito HTML

website:
  title: "Prova2"
  navbar:
      - href: index.qmd
        text: Home
      - text: Project
        menu:
      - href: index.qmd
        text: Home
      - href: VAIAK1.qmd
        text: Home
      - href: VAIAK2.qmd
        text: Home
      - href: VAIAK3.qmd
        text: Home
      - href: VAIAK4.qmd
        text: Home

format:
  html:
    theme: cosmo 